This notebook is used to download mirna expression profiles for other, non-TGCT, cancer patients. The idea behind using these expression profiles is to detect possible biomarkers that are specific to TGCTs.

In [2]:
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("TCGAbiolinks", ask = FALSE, verbose = TRUE)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

'getOption("repos")' replaces Bioconductor standard repositories, see
'help("repositories", package = "BiocManager")' for details.
Replacement repositories:
    CRAN: https://cran.rstudio.com

Bioconductor version 3.21 (BiocManager 1.30.26), R 4.5.1 (2025-06-13)

Installing package(s) 'BiocVersion', 'TCGAbiolinks'

system (cmd0): /usr/lib/R/bin/R CMD INSTALL

also installing the dependencies ‘plogr’, ‘png’, ‘Biostrings’, ‘RSQLite’, ‘KEGGREST’, ‘filelock’, ‘UCSC.utils’, ‘GenomeInfoDbData’, ‘matrixStats’, ‘abind’, ‘SparseArray’, ‘AnnotationDbi’, ‘BiocFileCache’, ‘BiocGenerics’, ‘GenomeInfoDb’, ‘XVector’, ‘R.oo’, ‘R.methodsS3’, ‘MatrixGenerics’, ‘Biobase’, ‘S4Arrays’, ‘DelayedArray’, ‘downloader’, ‘biomaRt’, ‘GenomicRanges’, ‘XML’, ‘plyr’, ‘IRanges’, ‘S4Vectors’, ‘R.utils’, ‘SummarizedExperiment’, ‘TCGAbiolinksGUI.data’


foundpkgs: plogr, png, Biostrings, RSQLite, KEGGREST, filelock, UCSC.utils, GenomeInfoDbData, matrixStats, abind, SparseArray, AnnotationDbi, BiocFileCache, BiocGenerics, GenomeInfoDb, XVector, R.oo, R.methodsS3, MatrixGenerics, Biobase, S4Arrays, DelayedArray, downloader, biomaRt, GenomicRanges, XML, plyr, IRanges, S4Vectors, R.utils, SummarizedExperiment, TCGAbiolinksGUI.data, BiocVersion, TCGAbiolinks, /tmp/RtmpaQqY2J/downloaded_packages/plogr_0.2.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/png_0.1-8.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/Biostrings_2.76.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/RSQLite_2.4.1.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/KEGGREST_1.48.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/filelock_1.0.3.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/UCSC.utils_1.4.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/GenomeInfoDbData_1.2.14.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/matrixStats_1.5.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/abind_1.4-8.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/SparseArray_1.8.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/AnnotationDbi_1.70.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/BiocFileCache_2.16.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/BiocGenerics_0.54.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/GenomeInfoDb_1.44.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/XVector_0.48.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/R.oo_1.27.1.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/R.methodsS3_1.8.2.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/MatrixGenerics_1.20.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/Biobase_2.68.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/S4Arrays_1.8.1.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/DelayedArray_0.34.1.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/downloader_0.4.1.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/biomaRt_2.64.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/GenomicRanges_1.60.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/XML_3.99-0.18.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/plyr_1.8.9.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/IRanges_2.42.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/S4Vectors_0.46.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/R.utils_2.13.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/SummarizedExperiment_1.38.1.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/TCGAbiolinksGUI.data_1.28.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/BiocVersion_3.21.1.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/TCGAbiolinks_2.36.0.tar.gz

files: /tmp/RtmpaQqY2J/downloaded_packages/plogr_0.2.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/png_0.1-8.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/Biostrings_2.76.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/RSQLite_2.4.1.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/KEGGREST_1.48.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/filelock_1.0.3.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/UCSC.utils_1.4.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/GenomeInfoDbData_1.2.14.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/matrixStats_1.5.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/abind_1.4-8.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/SparseArray_1.8.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/AnnotationDbi_1.70.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/BiocFileCache_2.16.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/BiocGenerics_0.54.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/GenomeInfoDb_1.44.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/XVector_0.48.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/R.oo_1.27.1.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/R.methodsS3_1.8.2.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/MatrixGenerics_1.20.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/Biobase_2.68.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/S4Arrays_1.8.1.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/DelayedArray_0.34.1.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/downloader_0.4.1.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/biomaRt_2.64.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/GenomicRanges_1.60.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/XML_3.99-0.18.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/plyr_1.8.9.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/IRanges_2.42.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/S4Vectors_0.46.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/R.utils_2.13.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/SummarizedExperiment_1.38.1.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/TCGAbiolinksGUI.data_1.28.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/BiocVersion_3.21.1.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/TCGAbiolinks_2.36.0.tar.gz

1): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/plogr_0.2.0.tar.gz''

2): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/png_0.1-8.tar.gz''

3): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/filelock_1.0.3.tar.gz''

4): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/GenomeInfoDbData_1.2.14.tar.gz''

5): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/matrixStats_1.5.0.tar.gz''

6): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/abind_1.4-8.tar.gz''

7): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/BiocGenerics_0.54.0.tar.gz''

8): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/R.methodsS3_1.8.2.tar.gz''

9): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/downloader_0.4.1.tar.gz''

10): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/XML_3.99-0.18.tar.gz''

11): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/plyr_1.8.9.tar.gz''

12): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/TCGAbiolinksGUI.data_1.28.0.tar.gz''

13): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/BiocVersion_3.21.1.tar.gz''

14): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/RSQLite_2.4.1.tar.gz''

15): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/R.oo_1.27.1.tar.gz''

16): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/MatrixGenerics_1.20.0.tar.gz''

17): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/Biobase_2.68.0.tar.gz''

18): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/S4Vectors_0.46.0.tar.gz''

19): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/UCSC.utils_1.4.0.tar.gz''

20): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/BiocFileCache_2.16.0.tar.gz''

21): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/IRanges_2.42.0.tar.gz''

22): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/R.utils_2.13.0.tar.gz''

23): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/GenomeInfoDb_1.44.0.tar.gz''

24): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/XVector_0.48.0.tar.gz''

25): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/S4Arrays_1.8.1.tar.gz''

26): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/Biostrings_2.76.0.tar.gz''

27): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/SparseArray_1.8.0.tar.gz''

28): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/GenomicRanges_1.60.0.tar.gz''

29): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/KEGGREST_1.48.0.tar.gz''

30): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/DelayedArray_0.34.1.tar.gz''

31): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/AnnotationDbi_1.70.0.tar.gz''

32): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/SummarizedExperiment_1.38.1.tar.gz''

33): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/biomaRt_2.64.0.tar.gz''

34): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/local/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/TCGAbiolinks_2.36.0.tar.gz''

Old packages: 'curl', 'evaluate'

added 2309 packages, from repos ‘https://bioconductor.org/packages/3.21/bioc/src/contrib’ to a total of 2309
added 928 packages, from repos ‘https://bioconductor.org/packages/3.21/data/annotation/src/contrib’ to a total of 3237
added 431 packages, from repos ‘https://bioconductor.org/packages/3.21/data/experiment/src/contrib’ to a total of 3668
added 27 packages, from repos ‘https://bioconductor.org/packages/3.21/workflows/src/contrib’ to a total of 3695
added 10 packages, from repos ‘https://bioconductor.org/packages/3.21/books/src/contrib’ to a total of 3705
added 22354 packages, from repos ‘https://cran.rstudio.com/src/contrib’ to a total of 26059

system (cmd0): /usr/lib/R/bin/R CMD INSTALL

foundpkgs: curl, evaluate, /tmp/RtmpaQqY2J/downloaded_packages/curl_6.4.0.tar.gz, /tmp/RtmpaQqY2J/downloaded_packages/evaluate_1.0.4.tar.gz

files: /tmp/RtmpaQqY2J/downloaded_packages/curl_6.4.0.tar.gz,
	/tmp/RtmpaQqY2J/downloaded_packages/evaluate_1.0.4.tar.gz

1): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/curl_6.4.0.tar.gz''

2): succeeded '/usr/lib/R/bin/R CMD INSTALL -l '/usr/lib/R/site-library' '/tmp/RtmpaQqY2J/downloaded_packages/evaluate_1.0.4.tar.gz''

In [3]:
library(TCGAbiolinks)
library(SummarizedExperiment)
library(dplyr)
library(tidyr)

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: GenomicRanges

Loading required package: stats4

Loading required package: BiocGenerics

Loading required package: generics


Attaching package: ‘generics’


The following objects are masked from ‘package:base’:

    as.difftime, as.factor, as.ordered, intersect, is.element, setdiff,
    setequal, union



Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, is.unsorted, lapply, Map, mapply, match, mget,
    order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
    rbind, Reduce, rownames, sapply, saveRDS, table, tapply, unique,
    unsplit, which.max, which.min


Loading required package: S4Vectors


Attaching package: ‘S4Vectors’


The following object is masked from ‘package:utils’:

    findMatches


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Loading required package: GenomeInfoDb

Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians



Attaching package: ‘dplyr’


The following object is masked from ‘package:Biobase’:

    combine


The following objects are masked from ‘package:GenomicRanges’:

    intersect, setdiff, union


The following object is masked from ‘package:GenomeInfoDb’:

    intersect


The following objects are masked from ‘package:IRanges’:

    collapse, desc, intersect, setdiff, slice, union


The following objects are masked from ‘package:S4Vectors’:

    first, intersect, rename, setdiff, setequal, union


The following objects are masked from ‘package:BiocGenerics’:

    combine, intersect, setdiff, setequal, union


The following object is masked from ‘package:generics’:

    explain


The following object is masked from ‘package:matrixStats’:

    count


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



Attaching package: ‘tidyr’


The following object is masked from ‘package:S4Vectors’:

    expand

In [5]:
patients <-read.csv2('https://raw.githubusercontent.com/Ignas12345/masters_project_data_and_notebooks/refs/heads/main/Data/sample_annotations/filtered_other_tcga_patients_clin_data.csv')
sumbitter_ids <- patients$submitter_id

In [9]:
sumbitter_ids

  [1] "TCGA-W3-AA21" "TCGA-AS-3778" "TCGA-IK-7675" "TCGA-ET-A39M" "TCGA-26-1438"
  [6] "TCGA-06-0187" "TCGA-CM-6674" "TCGA-27-1837" "TCGA-S9-A6WO" "TCGA-DV-5574"
 [11] "TCGA-P5-A72X" "TCGA-A3-3365" "TCGA-S9-A6U8" "TCGA-4V-A9QM" "TCGA-DX-AB2G"
 [16] "TCGA-TM-A7C5" "TCGA-FV-A4ZQ" "TCGA-DU-8163" "TCGA-BR-4279" "TCGA-P5-A5ET"
 [21] "TCGA-CE-A3MD" "TCGA-E3-A3DY" "TCGA-E1-A7YW" "TCGA-HT-7609" "TCGA-CJ-4908"
 [26] "TCGA-DD-A1EL" "TCGA-ET-A2MX" "TCGA-DU-6542" "TCGA-A4-A772" "TCGA-QR-A6H6"
 [31] "TCGA-BB-7866" "TCGA-CR-7385" "TCGA-02-0028" "TCGA-VM-A8CE" "TCGA-FG-8187"
 [36] "TCGA-P5-A5F6" "TCGA-D3-A8GB" "TCGA-DX-AB3C" "TCGA-GF-A769" "TCGA-D3-A8GV"
 [41] "TCGA-02-0026" "TCGA-KL-8340" "TCGA-FG-5963" "TCGA-VM-A8CB" "TCGA-FY-A3ON"
 [46] "TCGA-QU-A6IM" "TCGA-DB-A4XG" "TCGA-EM-A2CK" "TCGA-DJ-A2PQ" "TCGA-ET-A40Q"
 [51] "TCGA-FY-A3BL" "TCGA-DD-AAVZ" "TCGA-HT-7873" "TCGA-G6-A8L6" "TCGA-CV-5979"
 [56] "TCGA-P5-A730" "TCGA-A6-6141" "TCGA-ET-A3BU" "TCGA-QR-A70R" "TCGA-15-1444"
 [61] "TCGA-E1-5305" "TCGA-WY-A85B" "TCGA-WB-A817" "TCGA-WE-AA9Y" "TCGA-DJ-A2PR"
 [66] "TCGA-73-A9RS" "TCGA-B0-5697" "TCGA-MT-A51X" "TCGA-FG-8182" "TCGA-KM-A7Q6"
 [71] "TCGA-BP-4797" "TCGA-ZN-A9VO" "TCGA-DU-7299" "TCGA-B0-5084" "TCGA-ER-A2NE"
 [76] "TCGA-HW-8321" "TCGA-WB-A81G" "TCGA-DU-A7TI" "TCGA-32-4208" "TCGA-QH-A6X3"
 [81] "TCGA-EL-A3ZG" "TCGA-ET-A3BX" "TCGA-S9-A6U9" "TCGA-OR-A5JC" "TCGA-RC-A6M3"
 [86] "TCGA-S7-A7WQ" "TCGA-J8-A3YH" "TCGA-HT-7476" "TCGA-DD-AAVX" "TCGA-TM-A84L"
 [91] "TCGA-MR-A8JO" "TCGA-P5-A5F1" "TCGA-UB-A7MB" "TCGA-DD-A1EH" "TCGA-HT-7611"
 [96] "TCGA-DJ-A3VL" "TCGA-HT-7472" "TCGA-HT-7603" "TCGA-HW-7491" "TCGA-KL-8337"
[101] "TCGA-UD-AAC7" "TCGA-B9-4617" "TCGA-EE-A2MG" "TCGA-OR-A5JI" "TCGA-H2-A2K9"
[106] "TCGA-HT-7473" "TCGA-FG-8181" "TCGA-P5-A5EZ" "TCGA-TQ-A7RH" "TCGA-HW-7487"
[111] "TCGA-DD-A4NB" "TCGA-DB-A4XA" "TCGA-TQ-A7RK" "TCGA-ET-A39O" "TCGA-E1-A7Z4"
[116] "TCGA-HT-7690" "TCGA-LN-A4A4" "TCGA-HT-7478" "TCGA-DB-A4XC" "TCGA-KK-A7AW"
[121] "TCGA-HT-7605" "TCGA-D3-A8GE" "TCGA-HT-A61B" "TCGA-BP-5194" "TCGA-F7-A620"
[126] "TCGA-BA-6873" "TCGA-S7-A7WW" "TCGA-02-0080" "TCGA-HT-7483" "TCGA-J8-A3O2"
[131] "TCGA-WB-A822" "TCGA-KM-A7QA" "TCGA-SI-A71O" "TCGA-XU-A92X" "TCGA-02-0024"
[136] "TCGA-QR-A70I" "TCGA-KT-A74X" "TCGA-WY-A85A" "TCGA-OR-A5JW" "TCGA-P5-A5F0"
[141] "TCGA-SP-A6QD" "TCGA-CJ-4875" "TCGA-QH-A86X" "TCGA-DE-A4M9" "TCGA-HT-7856"
[146] "TCGA-2Z-A9JM" "TCGA-06-0129" "TCGA-HT-A5RB" "TCGA-QR-A6H2" "TCGA-DX-A6BH"
[151] "TCGA-EM-A2P1" "TCGA-S9-A7J2" "TCGA-ET-A25M" "TCGA-QR-A70N" "TCGA-19-5958"
[156] "TCGA-EM-A22Q" "TCGA-02-0014" "TCGA-02-0266" "TCGA-D3-A2JK" "TCGA-QR-A703"
[161] "TCGA-XU-A932" "TCGA-DB-A4XB" "TCGA-VD-A8KA" "TCGA-TM-A84Q" "TCGA-V4-A9EJ"
[166] "TCGA-TQ-A7RO" "TCGA-DU-A5TP" "TCGA-IB-AAUU" "TCGA-CR-7393" "TCGA-12-0773"
[171] "TCGA-VQ-A928" "TCGA-HT-8015" "TCGA-P5-A5EY" "TCGA-CV-7440" "TCGA-06-0221"
[176] "TCGA-DB-A64S" "TCGA-DU-A76O" "TCGA-HT-7469" "TCGA-ER-A3ES" "TCGA-X7-A8M7"
[181] "TCGA-EE-A3AG" "TCGA-QR-A6GZ" "TCGA-HD-7832" "TCGA-EE-A2A1" "TCGA-G9-6384"
[186] "TCGA-ED-A7XO" "TCGA-QR-A6GU" "TCGA-EL-A3CY" "TCGA-CV-A465" "TCGA-BB-A5HU"
[191] "TCGA-R6-A6L4" "TCGA-19-A60I" "TCGA-02-0102" "TCGA-FG-8191" "TCGA-OR-A5LM"
[196] "TCGA-FN-7833" "TCGA-DU-7013" "TCGA-DD-AACQ" "TCGA-DU-7011" "TCGA-BJ-A18Y"
[201] "TCGA-MJ-A850" "TCGA-HT-7858" "TCGA-08-0351" "TCGA-DD-A3A4" "TCGA-QT-A5XL"
[206] "TCGA-DD-AAVW" "TCGA-32-1973" "TCGA-BP-4758" "TCGA-ZB-A96R" "TCGA-TM-A84T"
[211] "TCGA-G3-AAV1" "TCGA-HT-7602" "TCGA-DJ-A3VJ" "TCGA-DB-5276" "TCGA-W2-A7HB"
[216] "TCGA-AZ-5403" "TCGA-SQ-A6I6" "TCGA-KN-8423" "TCGA-EM-A2CL" "TCGA-DB-A75O"
[221] "TCGA-TM-A84S" "TCGA-NP-A5H6" "TCGA-CN-6022" "TCGA-DH-5143" "TCGA-TQ-A7RV"
[226] "TCGA-BP-4777" "TCGA-DH-5142" "TCGA-CS-6666" "TCGA-S9-A7R7" "TCGA-14-1456"
[231] "TCGA-HT-8114" "TCGA-QR-A70Q" "TCGA-FS-A1Z7" "TCGA-Z4-A9VC" "TCGA-F6-A8O3"
[236] "TCGA-FS-A1ZR" "TCGA-DU-5853" "TCGA-CC-5263" "TCGA-X7-A8DG" "TCGA-OR-A5LE"
[241] "TCGA-HT-7676" "TCGA-S9-A6U6" "TCGA-CW-6097" "TCGA-KM-8442" "TCGA-GS-A9TX"
[246] "TCGA-S7-A7X1" "TCGA-GN-A263" "TCGA-GN-A267" "TCGA-EE-A29C" "TCGA-A3-A8OW"
[251] "TCGA-DV-5568" "TCGA-ER-A198" "TCGA-S9-A6U5" "TCGA-WY-A85C" "TCGA-ZC-AAA7"
[256] "TCGA-FG-7634" "TCGA-DU-A7TA" "TCGA-WB-A80P" "TCGA-02-0271" "TCGA-KO-8405"

In [10]:
query <- GDCquery(
  project = c("TCGA-ACC", "TCGA-BLCA", "TCGA-BRCA", "TCGA-CESC", "TCGA-CHOL",
              "TCGA-COAD", "TCGA-DLBC", "TCGA-ESCA", "TCGA-GBM", "TCGA-HNSC",
              "TCGA-KICH", "TCGA-KIRC", "TCGA-KIRP", "TCGA-LAML", "TCGA-LGG",
              "TCGA-LIHC", "TCGA-LUAD", "TCGA-LUSC", "TCGA-MESO", "TCGA-OV",
              "TCGA-PAAD", "TCGA-PCPG", "TCGA-PRAD", "TCGA-READ", "TCGA-SARC",
              "TCGA-SKCM", "TCGA-STAD", "TCGA-TGCT", "TCGA-THCA", "TCGA-THYM",
              "TCGA-UCEC", "TCGA-UCS", "TCGA-UVM"),  # You can also use "TCGA" for all
  data.category = "Transcriptome Profiling",
  data.type = "Isoform Expression Quantification",
  barcode = sumbitter_ids
)

--------------------------------------

o GDCquery: Searching in GDC database

--------------------------------------

Genome of reference: hg38

--------------------------------------------

oo Accessing GDC. This might take a while...

--------------------------------------------

ooo Project: TCGA-ACC

ooo Project: TCGA-BLCA

ooo Project: TCGA-BRCA

ooo Project: TCGA-CESC

ooo Project: TCGA-CHOL

ooo Project: TCGA-COAD

ooo Project: TCGA-DLBC

ooo Project: TCGA-ESCA

ooo Project: TCGA-GBM

ooo Project: TCGA-HNSC

ooo Project: TCGA-KICH

ooo Project: TCGA-KIRC

ooo Project: TCGA-KIRP

ooo Project: TCGA-LAML

ooo Project: TCGA-LGG

ooo Project: TCGA-LIHC

ooo Project: TCGA-LUAD

ooo Project: TCGA-LUSC

ooo Project: TCGA-MESO

ooo Project: TCGA-OV

ooo Project: TCGA-PAAD

ooo Project: TCGA-PCPG

ooo Project: TCGA-PRAD

ooo Project: TCGA-READ

ooo Project: TCGA-SARC

ooo Project: TCGA-SKCM

ooo Project: TCGA-STAD

ooo Project: TCGA-TGCT

ooo Project: TCGA-THCA

ooo Project: TCGA-THYM

ooo Project: TCGA-UCEC

ooo Project: TCGA-UCS

ooo Project: TCGA-UVM

--------------------

oo Filtering results

--------------------

ooo By data.type

ooo By barcode

----------------

oo Checking data

----------------

ooo Checking if there are duplicated cases

ooo Checking if there are results for the query

-------------------

o Preparing output

-------------------

In [14]:
GDCdownload(query)

Downloading data for project TCGA-ACC

GDCdownload will download 5 files. A total of 1.94785 MB

Downloading as: Mon_Jun_23_06_48_10_2025.tar.gz

Downloading: 220 kB

Downloading data for project TCGA-BLCA

All samples have been already downloaded

Downloading data for project TCGA-BRCA

All samples have been already downloaded

Downloading data for project TCGA-CESC

All samples have been already downloaded

Downloading data for project TCGA-CHOL

All samples have been already downloaded

Downloading data for project TCGA-COAD

GDCdownload will download 3 files. A total of 1.35196 MB

Downloading as: Mon_Jun_23_06_48_13_2025.tar.gz

Downloading: 150 kB

Downloading data for project TCGA-DLBC

GDCdownload will download: 391.313 KB

Downloading as: 076ba03c-ebcc-48e5-9c5c-64a138da3a4a.mirbase21.isoforms.quantification.txt

  |======================================================================| 100%

Downloading data for project TCGA-ESCA

GDCdownload will download 2 files. A total of 650.762 KB

Downloading as: Mon_Jun_23_06_48_16_2025.tar.gz

Downloading: 77 kB

Downloading data for project TCGA-GBM

GDCdownload will download 7 files. A total of 4.394355 MB

Downloading as: Mon_Jun_23_06_48_18_2025.tar.gz

Downloading: 490 kB

Downloading data for project TCGA-HNSC

GDCdownload will download 13 files. A total of 5.067436 MB

Downloading as: Mon_Jun_23_06_48_25_2025.tar.gz

Downloading: 570 kB

Downloading data for project TCGA-KICH

GDCdownload will download 6 files. A total of 2.41427 MB

Downloading as: Mon_Jun_23_06_48_31_2025.tar.gz

Downloading: 270 kB

Downloading data for project TCGA-KIRC

GDCdownload will download 15 files. A total of 4.962998 MB

Downloading as: Mon_Jun_23_06_48_34_2025.tar.gz

Downloading: 550 kB

Downloading data for project TCGA-KIRP

GDCdownload will download 3 files. A total of 852.844 KB

Downloading as: Mon_Jun_23_06_48_42_2025.tar.gz

Downloading: 100 kB

Downloading data for project TCGA-LAML

All samples have been already downloaded

Downloading data for project TCGA-LGG

GDCdownload will download 90 files. A total of 34.095128 MB

Downloading as: Mon_Jun_23_06_48_44_2025.tar.gz

Downloading: 3.9 MB

Downloading data for project TCGA-LIHC

GDCdownload will download 18 files. A total of 6.404775 MB

Downloading as: Mon_Jun_23_06_49_27_2025.tar.gz

Downloading: 740 kB

Downloading data for project TCGA-LUAD

GDCdownload will download: 344.648 KB

Downloading as: 0ab7c85e-6967-4841-a56e-6f010edc2350.mirbase21.isoforms.quantification.txt

  |======================================================================| 100%

Downloading data for project TCGA-LUSC

All samples have been already downloaded

Downloading data for project TCGA-MESO

GDCdownload will download 2 files. A total of 646.377 KB

Downloading as: Mon_Jun_23_06_49_36_2025.tar.gz

Downloading: 76 kB

Downloading data for project TCGA-OV

All samples have been already downloaded

Downloading data for project TCGA-PAAD

GDCdownload will download: 332.041 KB

Downloading as: 5946a27b-71ca-4c5a-ae20-92323615351c.mirbase21.isoforms.quantification.txt

  |======================================================================| 100%

Downloading data for project TCGA-PCPG

GDCdownload will download 21 files. A total of 8.391955 MB

Downloading as: Mon_Jun_23_06_49_38_2025.tar.gz

Downloading: 970 kB

Downloading data for project TCGA-PRAD

GDCdownload will download 4 files. A total of 1.092381 MB

Downloading as: Mon_Jun_23_06_49_49_2025.tar.gz

Downloading: 130 kB

Downloading data for project TCGA-READ

All samples have been already downloaded

Downloading data for project TCGA-SARC

GDCdownload will download 7 files. A total of 2.344885 MB

Downloading as: Mon_Jun_23_06_49_51_2025.tar.gz

Downloading: 280 kB

Downloading data for project TCGA-SKCM

GDCdownload will download 18 files. A total of 7.864776 MB

Downloading as: Mon_Jun_23_06_49_55_2025.tar.gz

Downloading: 880 kB

Downloading data for project TCGA-STAD

GDCdownload will download 2 files. A total of 670.925 KB

Downloading as: Mon_Jun_23_06_50_04_2025.tar.gz

Downloading: 77 kB

Downloading data for project TCGA-TGCT

All samples have been already downloaded

Downloading data for project TCGA-THCA

GDCdownload will download 32 files. A total of 14.636639 MB

Downloading as: Mon_Jun_23_06_50_06_2025.tar.gz

Downloading: 1.6 MB

Downloading data for project TCGA-THYM

GDCdownload will download 7 files. A total of 3.494503 MB

Downloading as: Mon_Jun_23_06_50_22_2025.tar.gz

Downloading: 390 kB

Downloading data for project TCGA-UCEC

All samples have been already downloaded

Downloading data for project TCGA-UCS

All samples have been already downloaded

Downloading data for project TCGA-UVM

GDCdownload will download 2 files. A total of 707.795 KB

Downloading as: Mon_Jun_23_06_50_25_2025.tar.gz

Downloading: 85 kB

In [15]:
data <- GDCprepare(query)

  |======================================================================| 100%

In [17]:
data_summarized <- data %>%
  mutate(miRNA_id_and_region = paste(miRNA_ID, miRNA_region, sep = ", "))

In [18]:
aggregated_data_rpm <- data_summarized %>%
  group_by(miRNA_id_and_region, barcode) %>%
  summarise(total_reads_per_million_miRNA_mapped = sum(reads_per_million_miRNA_mapped), .groups = "drop")

In [19]:
final_aggregated_data_rpm <- aggregated_data_rpm %>%
  pivot_wider(names_from = barcode, values_from = total_reads_per_million_miRNA_mapped)

In [20]:
head(final_aggregated_data_rpm)

  miRNA_id_and_region               TCGA-02-0026-01B-01R-A96R-41
1 hsa-let-7a-1, mature,MIMAT0000062 48067.590370
2 hsa-let-7a-1, mature,MIMAT0004481     4.008588
3 hsa-let-7a-1, precursor               0.435716
4 hsa-let-7a-1, stemloop                1.132861
5 hsa-let-7a-2, mature,MIMAT0000062 48143.753547
6 hsa-let-7a-2, mature,MIMAT0010195     3.660015
  TCGA-06-0129-01A-01R-A96R-41 TCGA-06-0187-01A-01R-A96R-41
1 60613.810214                 48648.734545
2     2.159806                     0.319960
3     0.159986                     0.426613
4     1.199892                     0.746573
5 60680.204219                 48795.062889
6     7.999278                     3.519559
  TCGA-06-0221-01A-01R-A96R-41 TCGA-15-1444-01A-02R-A96U-41
1 54641.922988                 24000.986700
2     1.379815                     2.264963
3     0.376313                           NA
4     1.128940                     0.926575
5 54608.054808                 24008.811117
6     4.766633                     5.559454
  TCGA-19-5958-01A-11R-A96U-41 TCGA-19-A60I-01A-12R-A96U-41
1 27291.309425                 41714.400456
2    15.527630                     1.940069
3     0.652421                           NA
4     2.000761                     3.341230
5 27322.625651                 41839.427147
6     1.739791                     5.065737
  TCGA-2Z-A9JM-01A-12R-A42U-13 TCGA-4V-A9QM-01A-11R-A42W-13 ⋯
1 7722.647506                  28792.304661                 ⋯
2   11.681920                     92.292384                 ⋯
3    0.359444                      0.648804                 ⋯
4    0.359444                      0.162201                 ⋯
5 7691.196183                  28554.355753                 ⋯
6    1.976941                      1.784211                 ⋯
  TCGA-WY-A85B-01A-11R-A36C-13 TCGA-WY-A85C-01A-11R-A36C-13
1 9949.150302                   9987.77713
2   17.870049                     23.29085
3          NA                           NA
4    0.117566                           NA
5 9913.527766                  10014.78900
6   10.816083                     16.40007
  TCGA-X7-A8DG-01A-11R-A42W-13 TCGA-X7-A8M7-01A-11R-A42W-13
1 14849.139293                 23043.686459
2    17.862511                    28.860215
3     0.168514                     0.919115
4     0.505543                     0.183823
5 14794.372166                 23070.340799
6    34.545421                    34.374905
  TCGA-XU-A92X-01A-11R-A42W-13 TCGA-XU-A932-01A-11R-A42W-13
1 23309.339477                 20730.382697
2    39.728005                    35.918183
3     0.328331                     1.016552
4     0.328330                     0.508276
5 23230.704294                 20752.238575
6    37.429689                    83.526718
  TCGA-Z4-A9VC-01A-11R-A37H-13 TCGA-ZB-A96R-01A-11R-A42U-13
1 29087.584789                 27476.372025
2    43.518231                    14.947689
3     1.200503                     0.314688
4           NA                     0.314688
5 28979.239407                 27463.155121
6     3.001257                    43.112284
  TCGA-ZC-AAA7-01A-11R-A42U-13 TCGA-ZN-A9VO-01A-11R-A404-13
1 9216.283686                  8306.706057
2   32.384023                    12.786574
3    0.835717                           NA
4    0.208929                     0.684996
5 9146.710271                  8362.647316
6    5.014301                     4.566635

In [21]:
write.csv2(final_aggregated_data_rpm, "TCGA_other_samples_mirna_isoform_data_rpm.csv", row.names = FALSE)

In [22]:
aggregated_data_raw_counts <- data_summarized %>%
  group_by(miRNA_id_and_region, barcode) %>%
  summarise(total_read_counts = sum(read_count), .groups = "drop")

In [23]:
final_aggregated_data_raw_counts <- aggregated_data_raw_counts %>%
  pivot_wider(names_from = barcode, values_from = total_read_counts)

In [24]:
head(final_aggregated_data_raw_counts)

  miRNA_id_and_region               TCGA-02-0026-01B-01R-A96R-41
1 hsa-let-7a-1, mature,MIMAT0000062 551593
2 hsa-let-7a-1, mature,MIMAT0004481     46
3 hsa-let-7a-1, precursor                5
4 hsa-let-7a-1, stemloop                13
5 hsa-let-7a-2, mature,MIMAT0000062 552467
6 hsa-let-7a-2, mature,MIMAT0010195     42
  TCGA-06-0129-01A-01R-A96R-41 TCGA-06-0187-01A-01R-A96R-41
1 757741                       456139
2     27                            3
3      2                            4
4     15                            7
5 758571                       457511
6    100                           33
  TCGA-06-0221-01A-01R-A96R-41 TCGA-15-1444-01A-02R-A96U-41
1 435610                       233126
2     11                           22
3      3                           NA
4      9                            9
5 435340                       233202
6     38                           54
  TCGA-19-5958-01A-11R-A96U-41 TCGA-19-A60I-01A-12R-A96U-41
1 627462                       387027
2    357                           18
3     15                           NA
4     46                           31
5 628182                       388187
6     40                           47
  TCGA-2Z-A9JM-01A-12R-A42U-13 TCGA-4V-A9QM-01A-11R-A42W-13 ⋯
1 42970                        177510                       ⋯
2    65                           569                       ⋯
3     2                             4                       ⋯
4     2                             1                       ⋯
5 42795                        176043                       ⋯
6    11                            11                       ⋯
  TCGA-WY-A85B-01A-11R-A36C-13 TCGA-WY-A85C-01A-11R-A36C-13
1 84626                        72472
2   152                          169
3    NA                           NA
4     1                           NA
5 84323                        72668
6    92                          119
  TCGA-X7-A8DG-01A-11R-A42W-13 TCGA-X7-A8M7-01A-11R-A42W-13
1 88118                        125358
2   106                           157
3     1                             5
4     3                             1
5 87793                        125503
6   205                           187
  TCGA-XU-A92X-01A-11R-A42W-13 TCGA-XU-A932-01A-11R-A42W-13
1 141987                       122357
2    242                          212
3      2                            6
4      2                            3
5 141508                       122486
6    228                          493
  TCGA-Z4-A9VC-01A-11R-A37H-13 TCGA-ZB-A96R-01A-11R-A42U-13
1 96918                        174626
2   145                            95
3     4                             2
4    NA                             2
5 96557                        174542
6    10                           274
  TCGA-ZC-AAA7-01A-11R-A42U-13 TCGA-ZN-A9VO-01A-11R-A404-13
1 44112                        36380
2   155                           56
3     4                           NA
4     1                            3
5 43779                        36625
6    24                           20

In [25]:
write.csv2(final_aggregated_data_raw_counts, "TCGA_other_samples_mirna_isoform_data_raw_counts.csv", row.names = FALSE)