In [1]:
import sys
!git clone https://github.com/Ignas12345/masters_project_helper_functions.git
sys.path.append('/content/masters_project_helper_functions')

Cloning into 'masters_project_helper_functions'...
remote: Enumerating objects: 89, done.
remote: Counting objects: 100% (89/89), done.
remote: Compressing objects: 100% (64/64), done.
remote: Total 89 (delta 45), reused 59 (delta 22), pack-reused 0 (from 0)
Receiving objects: 100% (89/89), 35.78 KiB | 2.56 MiB/s, done.
Resolving deltas: 100% (45/45), done.

In [2]:
import pandas as pd
import masters_project_helper_functions.utils as utils

In [3]:
url_gtex_rpm_counts = 'https://raw.githubusercontent.com/Ignas12345/masters_project_data_and_notebooks/refs/heads/main/Data/expression_values/GTEx_rpm_counts.csv'
url_tcga_tgct_rpm_counts = 'https://raw.githubusercontent.com/Ignas12345/masters_project_data_and_notebooks/refs/heads/main/Data/expression_values/TCGA_TGCT_mirna_isoform_data_rpm.csv'
url_tcga_non_tgct_rpm_counts = 'https://raw.githubusercontent.com/Ignas12345/masters_project_data_and_notebooks/refs/heads/main/Data/expression_values/TCGA_other_samples_mirna_isoform_data_rpm.csv'
url_TCGA_TGCT_divisions_by_experiment = "https://raw.githubusercontent.com/Ignas12345/masters_project_data_and_notebooks/refs/heads/main/Data/sample_annotations/TCGA_TGCT_divisions_by_experiment.csv"

TCGA_TGCT_divisions_by_experiment = pd.read_csv(url_TCGA_TGCT_divisions_by_experiment, index_col=0)

gtex_mirna_rpm_counts = pd.read_csv(url_gtex_rpm_counts, sep = ';', index_col=0)
tcga_tgct_mirna_rpm_counts = utils.format_data_frame(url_tcga_tgct_rpm_counts, sep = ';', decimal = ',', transpose = True).loc[TCGA_TGCT_divisions_by_experiment.index]
tcga_non_tgct_mirna_rpm_counts = utils.format_data_frame(url_tcga_non_tgct_rpm_counts, sep = ';', decimal = ',', transpose = True)

tcga_tgct_mirna_rpm_counts = utils.initial_pre_processing_pipeline(tcga_tgct_mirna_rpm_counts)
tcga_non_tgct_mirna_rpm_counts = utils.initial_pre_processing_pipeline(tcga_non_tgct_mirna_rpm_counts)

reading df from url: https://raw.githubusercontent.com/Ignas12345/masters_project_data_and_notebooks/refs/heads/main/Data/expression_values/TCGA_TGCT_mirna_isoform_data_rpm.csv
nan values filled with 0
column names truncated using: slice(None, 15, None)
df transposed
final shape of df: (156, 3689)

reading df from url: https://raw.githubusercontent.com/Ignas12345/masters_project_data_and_notebooks/refs/heads/main/Data/expression_values/TCGA_other_samples_mirna_isoform_data_rpm.csv
nan values filled with 0
column names truncated using: slice(None, 15, None)
df transposed
final shape of df: (260, 3645)

initial shape: (137, 3689)
shape after collapsing: (137, 2212)
initial shape: (137, 2212)
shape after filtering: (137, 2191)
initial shape: (260, 3645)
shape after collapsing: (260, 2220)
initial shape: (260, 2220)
shape after filtering: (260, 2200)

In [4]:
tcga_tgct_mirna_rpm_counts

,"hsa-let-7a-1, mature,MIMAT0000062","hsa-let-7a-1, mature,MIMAT0004481","hsa-let-7a-2, mature,MIMAT0010195","hsa-let-7b, mature,MIMAT0000063","hsa-let-7b, mature,MIMAT0004482","hsa-let-7c, mature,MIMAT0000064","hsa-let-7c, mature,MIMAT0026472","hsa-let-7d, mature,MIMAT0000065","hsa-let-7d, mature,MIMAT0004484","hsa-let-7e, mature,MIMAT0000066",...,"hsa-mir-95, mature,MIMAT0000094","hsa-mir-95, mature,MIMAT0026473","hsa-mir-96, mature,MIMAT0000095","hsa-mir-96, mature,MIMAT0004510","hsa-mir-98, mature,MIMAT0000096","hsa-mir-98, mature,MIMAT0022842","hsa-mir-99a, mature,MIMAT0000097","hsa-mir-99a, mature,MIMAT0004511","hsa-mir-99b, mature,MIMAT0000689","hsa-mir-99b, mature,MIMAT0004678"
sample,,,,,,,,,,,,,,,,,,,,,
TCGA-2G-AAEW-01,19976.575359,7.247227,1.744703,7813.180477,6.039356,746.866884,1.073664,134.073678,149.910209,597.225092,...,0.671040,0.000000,215.537865,5.099900,38.920289,0.268416,603.667069,2.549950,19868.538009,134.342095
TCGA-2G-AAEX-01,22444.440949,8.137024,2.525284,13315.820957,9.259374,1939.417883,7.295263,97.363717,136.365319,568.469420,...,0.561174,0.000000,88.665517,1.964109,30.864578,0.280587,740.749885,3.367044,23203.990169,127.386534
TCGA-2G-AAF1-01,23076.955877,12.333453,1.370384,9467.980531,5.633799,1024.133369,4.415681,142.824429,136.124775,518.309545,...,2.283972,0.152265,295.850601,3.197562,32.127885,0.304530,501.864941,2.436238,14445.670686,117.091669
TCGA-2G-AAF4-01,18361.403808,13.013041,3.408178,8300.462489,7.436024,1273.419216,7.745859,116.497718,129.820597,386.053611,...,1.549172,0.000000,274.513242,18.590062,35.940785,0.000000,573.813233,1.239337,32411.152672,164.831879
TCGA-2G-AAF6-01,24464.943436,15.996325,0.820324,6135.616023,6.972757,977.416468,4.101622,138.634817,182.932332,467.995044,...,1.640648,0.000000,263.324118,8.613406,53.731245,2.460973,269.886712,0.820324,7703.255866,41.426380
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-ZM-AA0D-01,20668.929427,19.225505,1.362437,7576.513341,8.174624,805.351777,5.298367,246.449754,175.603019,480.032045,...,2.422110,0.000000,334.099881,4.692840,52.680907,0.302764,220.109301,1.059674,15884.504079,75.236811
TCGA-ZM-AA0E-01,10986.202447,17.300611,1.572782,4918.878222,5.347461,323.678701,1.887340,220.975983,170.646934,270.204085,...,2.831010,0.000000,612.913458,4.089234,41.364188,0.629113,398.857718,3.931957,13881.381033,68.258773
TCGA-ZM-AA0F-01,25219.786607,14.213302,4.138050,7788.976798,10.165206,940.416509,7.016692,267.893665,230.201442,550.360457,...,0.719661,0.000000,131.338064,1.799152,69.807082,0.809619,369.005982,1.889109,10578.021513,31.215279
TCGA-ZM-AA0H-01,17815.935398,20.460527,3.788986,5504.259012,11.366956,456.951635,3.157489,313.096490,231.001808,331.662519,...,0.757799,0.000000,171.388438,3.410088,73.632619,1.262996,143.223648,0.378900,10782.694494,49.383109
TCGA-ZM-AA0N-01,25701.102073,16.152230,3.992685,8777.738962,8.348344,1159.330864,4.718628,268.054426,143.736700,658.793211,...,1.633371,0.000000,163.337160,3.811201,55.353150,0.725943,450.629075,1.451886,18399.386580,76.224011

In [5]:
tcga_non_tgct_mirna_rpm_counts

,"hsa-let-7a-1, mature,MIMAT0000062","hsa-let-7a-1, mature,MIMAT0004481","hsa-let-7a-2, mature,MIMAT0010195","hsa-let-7b, mature,MIMAT0000063","hsa-let-7b, mature,MIMAT0004482","hsa-let-7c, mature,MIMAT0000064","hsa-let-7c, mature,MIMAT0026472","hsa-let-7d, mature,MIMAT0000065","hsa-let-7d, mature,MIMAT0004484","hsa-let-7e, mature,MIMAT0000066",...,"hsa-mir-95, mature,MIMAT0000094","hsa-mir-95, mature,MIMAT0026473","hsa-mir-96, mature,MIMAT0000095","hsa-mir-96, mature,MIMAT0004510","hsa-mir-98, mature,MIMAT0000096","hsa-mir-98, mature,MIMAT0022842","hsa-mir-99a, mature,MIMAT0000097","hsa-mir-99a, mature,MIMAT0004511","hsa-mir-99b, mature,MIMAT0000689","hsa-mir-99b, mature,MIMAT0004678"
TCGA-02-0026-01,145095.640547,9.498609,3.660015,115423.809722,87.491793,85131.344878,6.100024,14909.682152,154.330643,4339.645231,...,283.564040,0.000000,53.854509,1.481435,558.326612,0.000000,55530.535767,323.911352,5529.411620,236.506699
TCGA-06-0129-01,182403.539913,4.319612,7.999278,112637.515592,50.715423,108919.691086,8.239257,12982.028503,136.467686,4284.973327,...,200.621896,0.000000,14.718672,0.479957,578.587789,0.000000,51966.830517,313.811684,1746.162427,215.820526
TCGA-06-0187-01,147214.418160,1.066533,3.519559,219866.760151,141.742250,113447.659998,2.026414,11492.640813,194.642293,3902.764604,...,192.615880,0.000000,3.306252,0.000000,72.524253,0.213307,20792.382906,188.243094,7746.656580,315.053880
TCGA-06-0221-01,164507.925404,2.257879,4.766633,184025.657531,101.729986,126678.419344,1.881566,9751.151643,124.057899,2933.862712,...,142.497242,0.000000,7.902577,0.000000,204.087163,0.000000,19241.643716,150.274383,3479.015024,294.026004
TCGA-15-1444-01,72862.307560,4.426973,5.559454,141675.891247,104.085335,74621.154095,2.985633,5981.354828,126.117244,3214.291010,...,147.943249,0.000000,4.324020,0.000000,157.003101,0.000000,25226.434502,234.114788,12683.585527,348.495406
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TCGA-XU-A932-01,62248.075025,69.633836,83.526718,13546.237798,17.281389,5014.144475,34.054504,591.802894,1121.934947,1302.372987,...,5.760463,0.169425,98.266726,0.000000,114.362140,3.049657,2072.072545,5.252186,20823.058387,49.980489
TCGA-Z4-A9VC-01,87027.755930,82.834700,3.001257,19829.606623,32.713704,5990.509423,114.047776,336.440935,587.946291,3712.555190,...,1.200503,0.000000,0.000000,0.000000,105.644256,2.100880,1453.508875,7.203017,26896.667015,57.023887
TCGA-ZB-A96R-01,82481.196977,30.682100,43.112284,20808.915493,19.825358,11029.507211,32.570229,466.367933,702.384093,735.898389,...,7.867205,0.000000,52.080899,0.000000,435.056454,7.237829,3390.765502,8.653926,5581.939539,17.779883
TCGA-ZC-AAA7-01,27565.906179,64.976973,5.014301,13760.075350,27.160792,810.018403,11.073246,506.026456,527.755093,672.543008,...,9.192883,0.208929,65.185902,0.208929,148.966499,1.253575,256.982882,1.671433,16443.352720,50.769789
TCGA-ZN-A9VO-01,25074.242046,23.061499,4.566635,14391.744991,9.589930,7078.281685,9.361600,162.115485,256.644797,1616.816536,...,26.029810,0.456663,8.448272,0.000000,59.822897,0.913326,1474.565910,6.393287,33757.695349,128.322397

In [6]:
gtex_mirna_rpm_counts['hsa-let-7a-1, mature,MIMAT0004481']

GTEX-11EQ9-1926-SM-EVLQ3     88.112744
GTEX-11LCK-2326-SM-DEUQS     88.444086
GTEX-11NSD-1026-SM-EBBEU     87.831701
GTEX-11O72-0726-SM-EBB7R     94.409727
GTEX-11P7K-1026-SM-EVLQP     89.448865
                               ...
GTEX-ZU9S-2426-SM-GMKHW     100.070301
GTEX-ZVP2-1026-SM-GH6FX     124.483793
GTEX-ZVTK-0126-SM-EV6TS      49.181952
GTEX-ZYT6-2726-SM-EVLK1      57.072584
GTEX-ZZ64-1126-SM-DECQM      68.366484
Name: hsa-let-7a-1, mature,MIMAT0004481, Length: 111, dtype: float64

In [7]:
#concatenate all 3 data frames in axis 0:
mirna_rpm_counts = pd.concat([tcga_tgct_mirna_rpm_counts, tcga_non_tgct_mirna_rpm_counts, gtex_mirna_rpm_counts], axis=0)
#filter columns that have nan values:
for feature in mirna_rpm_counts.columns:
  if mirna_rpm_counts[feature].isna().sum() > 0:
    mirna_rpm_counts.drop(feature, axis=1, inplace=True)

In [8]:
mirna_rpm_counts

,"hsa-let-7a-1, mature,MIMAT0004481","hsa-let-7a-2, mature,MIMAT0010195","hsa-let-7b, mature,MIMAT0000063","hsa-let-7b, mature,MIMAT0004482","hsa-let-7c, mature,MIMAT0026472","hsa-let-7d, mature,MIMAT0000065","hsa-let-7d, mature,MIMAT0004484","hsa-let-7e, mature,MIMAT0000066","hsa-let-7e, mature,MIMAT0004485","hsa-let-7f-1, mature,MIMAT0004486",...,"hsa-mir-95, mature,MIMAT0000094","hsa-mir-95, mature,MIMAT0026473","hsa-mir-96, mature,MIMAT0000095","hsa-mir-96, mature,MIMAT0004510","hsa-mir-98, mature,MIMAT0000096","hsa-mir-98, mature,MIMAT0022842","hsa-mir-99a, mature,MIMAT0000097","hsa-mir-99a, mature,MIMAT0004511","hsa-mir-99b, mature,MIMAT0000689","hsa-mir-99b, mature,MIMAT0004678"
TCGA-2G-AAEW-01,7.247227,1.744703,7813.180477,6.039356,1.073664,134.073678,149.910209,597.225092,1.610495,1.476287,...,0.671040,0.000000,215.537865,5.099900,38.920289,0.268416,603.667069,2.549950,19868.538009,134.342095
TCGA-2G-AAEX-01,8.137024,2.525284,13315.820957,9.259374,7.295263,97.363717,136.365319,568.469420,1.402935,0.561174,...,0.561174,0.000000,88.665517,1.964109,30.864578,0.280587,740.749885,3.367044,23203.990169,127.386534
TCGA-2G-AAF1-01,12.333453,1.370384,9467.980531,5.633799,4.415681,142.824429,136.124775,518.309545,1.827179,1.065855,...,2.283972,0.152265,295.850601,3.197562,32.127885,0.304530,501.864941,2.436238,14445.670686,117.091669
TCGA-2G-AAF4-01,13.013041,3.408178,8300.462489,7.436024,7.745859,116.497718,129.820597,386.053611,1.859006,0.619669,...,1.549172,0.000000,274.513242,18.590062,35.940785,0.000000,573.813233,1.239337,32411.152672,164.831879
TCGA-2G-AAF6-01,15.996325,0.820324,6135.616023,6.972757,4.101622,138.634817,182.932332,467.995044,2.460973,0.410162,...,1.640648,0.000000,263.324118,8.613406,53.731245,2.460973,269.886712,0.820324,7703.255866,41.426380
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
GTEX-ZU9S-2426-SM-GMKHW,100.070301,0.000000,24424.260766,64.891942,3.706608,1541.172685,245.682004,195.042430,31.519528,5.561657,...,179.302283,0.000000,42.939292,0.000000,888.505372,2.473082,214672.533155,40.800217,7100.022153,378.336613
GTEX-ZVP2-1026-SM-GH6FX,124.483793,0.000000,17747.103206,49.789708,4.149225,1367.989038,189.516847,164.432111,20.741967,8.302858,...,171.807738,0.000000,66.877826,0.000000,783.930781,1.383451,223671.352584,14.512232,7820.887704,506.583026
GTEX-ZVTK-0126-SM-EV6TS,49.181952,10.714868,30503.861757,67.466772,0.000000,1684.518576,334.625718,240.841827,32.127042,2.138738,...,182.244349,0.000000,25.491683,0.000000,644.096961,0.000000,231053.943428,56.062764,6212.007343,372.747485
GTEX-ZYT6-2726-SM-EVLK1,57.072584,3.266348,17326.315313,38.350972,1.629849,1306.509091,134.569100,178.289026,16.316867,4.897658,...,192.207201,0.000000,29.636992,0.000000,653.274922,0.543602,192314.876419,40.831857,5933.605297,401.805462
GTEX-ZZ64-1126-SM-DECQM,68.366484,0.000000,11296.652612,29.833717,7.465613,1220.437286,152.727806,103.385018,4.959054,4.352961,...,181.177896,0.000000,38.080428,0.000000,713.631116,0.000000,245649.769369,10.147210,6745.723287,369.549627

In [9]:
#save to csv:
mirna_rpm_counts.to_csv('tgct_non_tgct_gtex_combined_mirna_rpm_counts.csv', sep = ';')

In [10]:
sample_label_dict = {}
#create a label dict 'TGCT' vs 'non_TGCT':
for sample in mirna_rpm_counts.index:
  if sample in tcga_tgct_mirna_rpm_counts.index:
    sample_label_dict[sample] = 'TGCT'
  else:
    sample_label_dict[sample] = 'non_TGCT'

In [11]:
sample_label_dict = pd.DataFrame.from_dict(sample_label_dict, orient='index', columns=['label'])
sample_label_dict.to_csv('TGCT_vs_non_TGCT_labels.csv', sep = ';')